# Generated by Django 3.0.6 on 2020-05-21 17:27

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reference_id', models.CharField(max_length=30)),
                ('user_type', models.IntegerField(default=1)),
                ('date_expiry', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 17, 37, 55, 90925))),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('amount_outstanding', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('orderstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodvendor.OrderStatus')),
            ],
            bases=('foodvendor.orderstatus',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('items_ordered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('amount_due', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('amount_outstanding', models.FloatField(default=0.0)),
                ('paid', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cancel_expiry', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 17, 37, 55, 96145))),
                ('delivery_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 17, 27, 55, 96196))),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Customer')),
                ('order_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodvendor.OrderStatus')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField()),
                ('is_recurring', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('freq_of_reocurrence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[], size=8)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Vendor')),
            ],
        ),
    ]
