# Generated by Django 3.0.6 on 2020-05-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0003_auto_20200517_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
