# Generated by Django 3.0.6 on 2020-05-23 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0003_auto_20200523_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodvendor.MessageStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auth',
            name='date_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 4, 5, 12, 974561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 4, 5, 12, 978669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 3, 55, 12, 978712, tzinfo=utc)),
        ),
    ]
