# Generated by Django 3.0.6 on 2020-05-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0004_auto_20200517_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_name',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField()),
                ('is_recurring', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('frequencyOfReocurrence', models.CharField(max_length=255)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Vendor')),
            ],
        ),
    ]
