# Generated by Django 3.0.6 on 2020-05-18 02:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='freq_of_reocurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'], size=8),
        ),
    ]
