# Generated by Django 3.0.6 on 2020-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0006_menu_freq_of_reocurrence'),
        ('foodvendor', '0005_auto_20200518_1244'),
    ]

    operations = [
    ]
