# Generated by Django 3.0.6 on 2020-05-18 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0007_merge_20200518_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='frequencyOfReocurrence',
        ),
        migrations.AddField(
            model_name='menu',
            name='freq_of_reocurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
