# Generated by Django 3.0.6 on 2020-05-18 18:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0008_auto_20200518_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('orderstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodvendor.OrderStatus')),
            ],
            bases=('foodvendor.orderstatus',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('items_ordered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=8)),
                ('amount_due', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('amount_outstanding', models.FloatField(default=0.0)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Customer')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.OrderStatus')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvendor.Vendor')),
            ],
        ),
    ]
