# Generated by Django 3.0.6 on 2020-05-23 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0008_auto_20200523_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='avaliable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='date_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 22, 22, 35, 649830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 22, 22, 35, 654987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 22, 12, 35, 655040, tzinfo=utc)),
        ),
    ]
