# Generated by Django 3.0.6 on 2020-05-25 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodvendor', '0010_auto_20200525_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='foodvendor.PaymentStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auth',
            name='date_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 25, 15, 3, 3, 759751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 25, 15, 3, 3, 762149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 25, 14, 53, 3, 762169, tzinfo=utc)),
        ),
    ]
